#ifndef MULTIREL_ENSEMBLE_THREADUTILSFITPARAMS_HPP_
#define MULTIREL_ENSEMBLE_THREADUTILSFITPARAMS_HPP_

namespace multirel
{
namespace ensemble
{
// ----------------------------------------------------------------------------

struct ThreadutilsFitParams
{
    /// The communicator used.
    multithreading::Communicator& comm_;

    /// The ensemble to be fitted.
    ensemble::DecisionTreeEnsemble& ensemble_;

    /// Contains the subfeatures generated by the propositionalization.
    const std::optional<const helpers::FeatureContainer>& feature_container_;

    /// For logging the progress.
    std::shared_ptr<const logging::AbstractLogger> logger_;

    /// The peripheral tables.
    const std::vector<containers::DataFrame>& peripheral_;

    /// The population table.
    const containers::DataFrame& population_;

    /// For training text columns more efficiently.
    const helpers::RowIndexContainer& row_indices_;

    /// The thread number of this thread.
    const size_t this_thread_num_;

    /// Designates a fixed column to each row in the population table.
    const std::vector<size_t>& thread_nums_;

    /// For processing text columns more efficiently.
    const helpers::WordIndexContainer& word_indices_;
};

// ----------------------------------------------------------------------------
}  // namespace ensemble
}  // namespace multirel

// ----------------------------------------------------------------------------
#endif  // MULTIREL_ENSEMBLE_THREADUTILSFITPARAMS_HPP_
