#ifndef RELBOOST_ENSEMBLE_THREADUTILSTRANSFORMPARAMS_HPP_
#define RELBOOST_ENSEMBLE_THREADUTILSTRANSFORMPARAMS_HPP_

// ----------------------------------------------------------------------------

#include <memory>
#include <optional>
#include <vector>

// ----------------------------------------------------------------------------

#include "helpers/helpers.hpp"
#include "logging/logging.hpp"
#include "multithreading/multithreading.hpp"

// ----------------------------------------------------------------------------

#include "relboost/containers/containers.hpp"

// ----------------------------------------------------------------------------

#include "relboost/ensemble/DecisionTreeEnsemble.hpp"

// ----------------------------------------------------------------------------

namespace relboost {
namespace ensemble {

struct ThreadutilsTransformParams {
  /// The communicator used.
  multithreading::Communicator* comm_ = nullptr;

  /// The ensemble to be fitted.
  const ensemble::DecisionTreeEnsemble ensemble_;

  /// Contains the subfeatures generated by the propositionalization.
  const std::optional<const helpers::FeatureContainer> feature_container_;

  /// The features to build.
  containers::Features* features_ = nullptr;

  /// Designates which features to build.
  const std::vector<size_t> index_;

  /// For logging the progress.
  std::shared_ptr<const logging::AbstractLogger> logger_;

  /// The peripheral tables.
  const std::vector<containers::DataFrame> peripheral_;

  /// The population table.
  const containers::DataFrame population_;

  /// The thread number of this thread.
  const size_t this_thread_num_;

  /// Designates a fixed column to each row in the population table.
  const std::vector<size_t> thread_nums_;

  /// For processing text columns more efficiently.
  const std::optional<helpers::WordIndexContainer> word_indices_;
};

}  // namespace ensemble
}  // namespace relboost

// ----------------------------------------------------------------------------
#endif  // RELBOOST_ENSEMBLE_THREADUTILSTRANSFORMPARAMS_HPP_
