#ifndef AUTOSQL_AGGREGATIONS_INTERMEDIATEAGGREGATIONIMPL_HPP_
#define AUTOSQL_AGGREGATIONS_INTERMEDIATEAGGREGATIONIMPL_HPP_

namespace autosql
{
namespace aggregations
{
// ----------------------------------------------------------------------------

struct IntermediateAggregationImpl
{
    // --------------------------------------

    IntermediateAggregationImpl(
        const size_t _nrows,
        const AggregationIndex& _index,
        optimizationcriteria::OptimizationCriterion* _parent )
        : count_( std::vector<Float>( _nrows ) ),
          index_( _index ),
          parent_( _parent ),
          updates_current_( containers::IntSet( _nrows ) ),
          updates_stored_( containers::IntSet( _nrows ) ),
          yhat_( std::vector<Float>( _nrows ) ),
          yhat_committed_( std::vector<Float>( _nrows ) ),
          yhat_stored_( std::vector<Float>( _nrows ) )
    {
    }

    ~IntermediateAggregationImpl() = default;

    // --------------------------------------

    /// Trivial accessor
    const AggregationIndex& index() const { return index_; }

    // --------------------------------------

    /// Vector counts - count_ remains unchanged, so count_stored_ and
    /// count_committed_ is not needed
    std::vector<Float> count_;

    /// Used to map ix_input to ix_aggregation
    const AggregationIndex index_;

    /// The parent of this IntermediateAggregation can
    /// be either another aggregation or the final
    /// optimization criterion.
    optimizationcriteria::OptimizationCriterion* const parent_;

    /// The sample weights generated by the parent.
    std::shared_ptr<std::vector<Float>> sample_weights_parent_;

    /// Vector sums
    std::vector<Float> sum_;

    /// Vector containing sums that have been
    /// committed
    std::vector<Float> sum_committed_;

    /// Vector sum_cubed_
    std::vector<Float> sum_cubed_;

    /// Vector containing sum_cubed_ that have been
    /// committed
    std::vector<Float> sum_cubed_committed_;

    /// Vector sum_squared_
    std::vector<Float> sum_squared_;

    /// Vector containing sum_squared_ that have been
    /// committed
    std::vector<Float> sum_squared_committed_;

    /// Contains the population_ix of all samples that have been updated
    /// since the last time we had a new critical value. Unlike
    /// updates_stored_, updates_current_ will be cleared every time we get
    /// to a new critical value.
    containers::IntSet updates_current_;

    /// Contains the population_ix of all samples that have been updated
    /// since the last commit. Will be cleared by revert_to_commit(),
    /// commit() or clear.
    containers::IntSet updates_stored_;

    /// Vector containing predictions
    std::vector<Float> yhat_;

    /// Vector containing predictions that have been
    /// committed
    std::vector<Float> yhat_committed_;

    /// Vector containing predictions that have been
    /// stored, but not yet committed
    std::vector<Float> yhat_stored_;
};

// ----------------------------------------------------------------------------
}  // namespace aggregations
}  // namespace autosql

#endif  // AUTOSQL_AGGREGATIONS_INTERMEDIATEAGGREGATIONIMPL_HPP_
