#!/usr/bin/env bash

SCRIPTS_DIR=$(dirname -- "$(realpath -- "$0")")
OUTPUT_DIR=${GETML_BUILD_OUTPUT_DIR:-build}
VERSION=${GETML_VERSION:-$(<"$SCRIPTS_DIR/../VERSION")}
PLATFORM=${GETML_BUILD_PLATFORM}

parse_opt_multiple_args() {
  while [[ ${OPTIND} -le $# && ${!OPTIND:0:1} != "-" ]]; do
    OPTARG[i]=${!OPTIND}
    ((OPTIND++))
    ((i++))
  done
}

process_build_args() {
  processed=""
  for arg in "$@"; do
    processed+=" --set $target.args.${arg}"
  done
  build_args=$processed

}

show_help() {
  cat <<-EOF
		Build utilities

		Usage:
		  build <subcommand> [options]

		Subcommands:
		  [a]ll       Build all (whole package, [p]ackage + [py]thon API + tar+gz [ar]chive)
		  [c]li       Build CLI
		  [e]ngine    Build Engine
		  [p]ackage   Export runnable [e]ngine + [c]li package
		  [py]thon    Package Python API
		  [r]untime   Build Docker runtime image
		  [ar]chive   Create tar.gz archive of [p]ackage

		Options:
		  -b <args>       Specify build args (-b KEY=VALUE); passed to Docker build
		  -h              Show help (this message)
		  -o <path>       Set output path (default: build); passed to Docker build
		  -p <platform>   Set the target platform for the build (default is your current platform).
		                  Valid options: linux/amd64, linux/arm64
	EOF
}


process_opts() {
  while getopts ":b:hop:" opt; do
    case ${opt} in
    b)
      parse_opt_multiple_args "$@"
      process_build_args "${OPTARG[@]}"
      ;;
    h)
      show_help
      exit 0
      ;;
    o)
      output="$OPTARG"
      ;;
    p)
      PLATFORM="$OPTARG"
      ;;
    \?)
      echo "Invalid option: -$OPTARG" >&2
      exit 1
      ;;
    esac
  done
}

if [[ -z $1 || $1 = "-h" ]]; then
  show_help
  exit 0
fi

while [[ "$#" -gt 0 ]]; do
  case "$1" in
  a | all)
    target="all"
    shift
    ;;
  c | cli)
    target="cli"
    shift
    ;;
  e | engine)
    target="engine"
    shift
    ;;
  p | package)
    target="package"
    shift
    ;;
  py | python)
    target="python"
    shift
    ;;
  r | runtime)
    target="runtime"
    shift
    ;;
  ar | archive)
    target="archive"
    shift
    ;;
  --)
    shift
    break
    ;;
  -*)
    process_opts "$@"
    shift $((OPTIND - 1))
    ;;
  *)
    echo "Unrecognized subcommmand: $1" >&2
    exit 1
    ;;
  esac
done

(
  export GETML_VERSION=${VERSION}
  export GETML_BUILD_OUTPUT_DIR=${OUTPUT_DIR}

  if [[ -n $PLATFORM ]]; then
    build_args+=" --set $target.platform=$PLATFORM"
  fi

  cd "${SCRIPTS_DIR}/.."
  docker buildx bake $target \
    $build_args \
    "${@}"
)
