#ifndef RELMT_ENSEMBLE_THREADUTILSFITPARAMS_HPP_
#define RELMT_ENSEMBLE_THREADUTILSFITPARAMS_HPP_

// ----------------------------------------------------------------------------

#include <memory>
#include <optional>
#include <vector>

// ----------------------------------------------------------------------------

#include "helpers/helpers.hpp"
#include "logging/logging.hpp"
#include "multithreading/multithreading.hpp"

// ----------------------------------------------------------------------------

#include "relmt/containers/containers.hpp"

// ----------------------------------------------------------------------------

#include "relmt/ensemble/DecisionTreeEnsemble.hpp"

// ----------------------------------------------------------------------------

namespace relmt {
namespace ensemble {
// ----------------------------------------------------------------------------

struct ThreadutilsFitParams {
  /// The communicator used.
  multithreading::Communicator* comm_ = nullptr;

  /// The ensemble to be fitted.
  ensemble::DecisionTreeEnsemble* ensemble_ = nullptr;

  /// Contains the subfeatures generated by the propositionalization.
  const std::optional<const helpers::FeatureContainer> feature_container_;

  /// For logging the progress.
  const std::shared_ptr<const logging::AbstractLogger> logger_;

  /// The peripheral tables.
  const std::vector<containers::DataFrame> peripheral_;

  /// The population table.
  const containers::DataFrame population_;

  /// For training text columns more efficiently.
  const helpers::RowIndexContainer row_indices_;

  /// The thread number of this thread.
  const size_t this_thread_num_;

  /// Designates a fixed column to each row in the population table.
  const std::vector<size_t> thread_nums_;

  /// For processing text columns more efficiently.
  const helpers::WordIndexContainer word_indices_;
};

// ----------------------------------------------------------------------------
}  // namespace ensemble
}  // namespace relmt

// ----------------------------------------------------------------------------
#endif  // RELMT_ENSEMBLE_THREADUTILSFITPARAMS_HPP_
